# Generated by Django 4.0.3 on 2022-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_color', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_info',
            name='color',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
