# Generated by Django 4.0.3 on 2022-05-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUsr', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('verify', models.BooleanField(default=True)),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MessageChecker.conditions')),
            ],
        ),
    ]
